version: 2

project_name: pchat

before:
  hooks:
    - go mod tidy

builds:
  - id: pchat
    main: ./cmd/pchat
    binary: pchat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore: []
    ldflags:
      - -s -w -X github.com/vijay-talsangi/PChat/cmd/pchat.version={{.Version}} -X github.com/vijay-talsangi/PChat/cmd/pchat.commit={{.Commit}} -X github.com/vijay-talsangi/PChat/cmd/pchat.date={{.Date}}

archives:
  - formats:
      - tar.gz
      - zip
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
